### ISSUE TITLE
Степень поста не видна на widget

### ISSUE THREAD

**Issue by dmatora** [alexeyismirnov/prayerbook_ios7#1]
И еще чтение дня туда бы вынести кнопкой, чтобы щелкнул и сразу открывалось

**Comment by alexeyismirnov** [comment]
Как не видна? Цвет дня - это и есть степень поста (в режиме "Большой виджет")

**Comment by dmatora** [comment]
Кстати, а где можно почитать какой цвет что значит? я не нашел
Но в любом случае, уверен Вы понимаете разницу в восприятии инфографики и цветографики.

В идеале хотелось бы видеть картинку как на http://days.pravoslavie.ru/Days/20170228.html в режиме маленький widget. Без всего остального что там сейчас есть я бы не страдал, а вот без такой картинки - таки да грустно. Полагаю не все со мной согласятся, но хотя бы опцией.

**Comment by alexeyismirnov** [comment]
Какой цвет соответствует какой степени поста - догадаться можно :) Среда и
пятница - постные дни, из этого исходите.

У меня нет цели быть "как pravoslavie.ru". Я не считаю, что это образец для
подражания.
